name: NYC-Affordability-Transit-Access
channels:
  - defaults
dependencies:
  - pip
  - requests
  - ipython
  - matplotlib
  - pandas
  - jupyterlab
  - ruff
  - notebook
  - openpyxl
  - scikit-learn
  - python=3.11
  - numpy
  - pytest

